[server]
address = "127.0.0.1"
port = 8080

[logging]
format = "json"
level = "INFO"

[metadata]
owner = "the_team"

[GoogleCloudDatastore]
namespace = "ale-jenkinslog"
project = "my-gcs-project"

[crawler]
logpattern = '''.*\[([\d{4}\-\d{2}\-\d{2}T\d{2}:\d{2}:\d{2}.\d*Z]*)\].*?\s(.*)$'''

[Pubsub]
subscription = "ale-subscription"
project = "my-gcs-project"
topic = "build-events-topic"
